### ISSUE TITLE
[Question] Using this version of optimus-manager

### ISSUE THREAD

**Issue by brandflake11** [Hyper-KVM/optimus-manager#2]
Hello,
I saw this on the pull request on the main optimus-manager repo, but I just switched from arch to artix with runit and am curious on how to get this setup on my system. 

Can I just install the optimus-manager and optimus-manager-qt applications from the AUR and copy the runit scripts to my runit services file, soft link them to be running, and be done? Or, do I have to makepkg -si the PKGBUILD from this version?

I tried to read the readme, but it didn't seem like the instructions were super clear.

Thank you very much for your help!

**Comment by Ann1kaB** [comment]
You have to install optimus-manager using the PKGBUILD in the package folder, thank you for pointing this out to me. 

Also optimus-manager-qt doesn't work with this version of optimus-manager due to no support for runit, openrc, and AMD as of now.

**Comment by brandflake11** [comment]
Thank you for your help with this!
