### ISSUE TITLE
No longer works after python upgrade to 3.9

### ISSUE THREAD

**Issue by Ingvix** [Hyper-KVM/optimus-manager#9]
**Describe the bug**
Optimus-manager no longer works due to python upgrade from 3.8 to 3.9, probably.

**System info**
Void Linux
DWM with startx
Thinkpad P50
Latest from your void-packages

**Logs**
```
Traceback (most recent call last):
  File "/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.3.5', 'console_scripts', 'optimus-manager')())
  File "/bin/optimus-manager", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: optimus-manager
```

**Comment by Ingvix** [comment]
Okay, so apparently the optimus-manager dirs in /usr/lib/python3.8/site-packages just need to moved to the 3.9's dir of same name. Did it manually for the time being and it's working.

**Comment by Ann1kaB** [comment]
Should be fixed now
Please use -f to build and install the package

**Comment by Ingvix** [comment]
`optimus-manager` now complains about not having module named 'py3nvml'. I installed it for my user with pip3 and it works fine after that. Not sure if there's a better way for that. 

Also issue https://github.com/Hyper-KVM/optimus-manager/issues/8 seems to be fixed. Not sure if I actually pulled the latest changes before I tried building it then as I noticed that the first pull today ended up with an error, but after hard reset everything worked fine.

**Comment by Ann1kaB** [comment]
> optimus-manager now complains about not having module named 'py3nvml'. I installed it for my user with pip3 and it works fine after that. Not sure if there's a better way for that.

I think I'm gonna have to add a mention in the Note for Void about it since it doesn't appear to be on the repos.

**Comment by Ingvix** [comment]
Alright. I guess this issue is solved then.
